version: 2

defaults: &defaults
  working_directory: ~/express-sequelize-crud
  docker:
    - image: circleci/node:12

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Check types
          command: yarn check-types

      - run:
          name: Run tests
          command: yarn test --coverage

      - run:
          name: Code coverage
          command: npx codecov

      - persist_to_workspace:
          root: ~/express-sequelize-crud
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/express-sequelize-crud
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/express-sequelize-crud/.npmrc
      - run:
          name: Publish package
          command: yarn publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
